version: '3'
services:
    web_thunder:
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        expose:
            - 8812
        environment:
            - PORT=8812
        deploy:
            resources:
                limits:
                    cpus: '2.0'
                    memory: 2048M
                
    nginx:
        restart: always
        build:
            context: ./nginx
            dockerfile: Dockerfile
        ports:
            - 5000:80
        depends_on:
            - web_thunder

        
    